### PR TITLE
WIP: Feature/theme support

### LINKED ISSUE #343: Prepare usage of color themes
Good day friends of neat design,

we would like to make it possible to create and load color themes into alva.

This issue should tackle one part of it: Load multiple json files, put all together, resolve references and flatten the structure. The outcome of this flow should be written into the store.

There is already a [PR for this issue](https://github.com/meetalva/alva/pull/342), there we did some preparations.

The most interesting file will be [`src/store/theme.ts`](https://github.com/meetalva/alva/blob/2dd1edae84d8ec8e0e2b8a50ea95deb685eaf497/src/store/theme.ts), where the magic should happen. (Have a look at the Todo comments)

For now we'll have 2 theme files [`default/colors.json`](https://github.com/meetalva/alva/blob/2dd1edae84d8ec8e0e2b8a50ea95deb685eaf497/src/themes/default/colors.json) and [`dark/colors.json`](https://github.com/meetalva/alva/blob/2dd1edae84d8ec8e0e2b8a50ea95deb685eaf497/src/themes/dark/colors.json), those two should be combined when dark theme is set in user preferences. The default theme should be always loaded and be overwritten by the theme from the preferences.

To set a theme in the preferences just open Alva go to menu point `Alva` in the OS menu, select `Preferences`. In the opened file add a line with `theme: dark`. After that you have to reload Alva.

For testing purposes there is also one example usage of the theme colors in the [`dropdown`](https://github.com/meetalva/alva/blob/2dd1edae84d8ec8e0e2b8a50ea95deb685eaf497/src/lsg/patterns/dropdown/index.tsx) component.

For now there is no need to add the new colors to all of the components, this will be done after this in a separate issue.

### PR DESCRIPTION
**Pull request by LKuechler**
Closes #343

### CODE REVIEW

**Comment by TheReincarnator** [comment]
Please ignore all above title changes and reviews, I am testing the WIP GitHub plugin.

**Comment by tilmx** [comment]
Reopened for collaboration

**Comment by agustif** [comment]
Hi guys! Love to see there's already a PR on this and support for a Dark theme is coming.

I would love to still collaborate adding some themes myself, copying from my favourites from my IDE's and terminal config files.

Is there any documentation on that? Maybe I could help document my process if you let me know which files should I are where and based on what.

Thanks in advance for reading, and keep on making awesome software open source!

**Comment by marionebl** [comment]
Closing as discussed with @LKuechler in person.

**Pull request closed without merging**
