### PR TITLE
feat: create projects without explicit path

### PR DESCRIPTION
**Pull request by marionebl**
This changes the basic behavior to ask for a save path on quit / window close / save for draft projects instead of asking up front. 

Draft projects are saved in the application support files when first created and marked as draft. When one of the following events occur for a draft project, the user is asked for a path to save to:

* `Cmd+S` (draft projects)
* `Cmd+Shift+S` (all projects)
* Any dialog schedules a save transaction

Additionally, when trying to close a window with a draft project active the user is asked wether the current project should be saved, discarded or the close canceled.

<details>
<summary>Dialog</summary>
screen shot 2018-09-14 at 22 47 40
</details>

### CODE REVIEW

**Comment by tilmx** [comment]
@marionebl Looks great! I stumbled across just two thingies:

- [ ] Approx a second after creating a new file, the name jumps from "New Project" to a long uuid. See attached image:
alva

- [ ] When hitting cmd+s, Alva shows the save dialog bound on the same window (not as a separate view). but when I try to close Alva, click on the upcoming "Do you want to save?"-Dialog on "Save" – it is a separate window. Can we bind this save dialog also to the main window?

**Comment by marionebl** [comment]
> When hitting cmd+s, Alva shows the save dialog bound on the same window (not as a separate view). but when I try to close Alva, click on the upcoming "Do you want to save?"-Dialog on "Save" – it is a separate window. Can we bind this save dialog also to the main window?

I am pretty sure this is caused be the "Do you want to save" dialog box still being active when we init the save select dialog, causing it to detach itself from the window. Adding a timeout before triggering the save transaction might solve this, but I'd rather live with the current state.

**Comment by tilmx** [comment]
> I am pretty sure this is caused be the "Do you want to save" dialog box still being active when we init the save select dialog, causing it to detach itself from the window. Adding a timeout before triggering the save transaction might solve this, but I'd rather live with the current state.

Okay, let’s do that!

**Comment by marionebl** [comment]
> Approx a second after creating a new file, the name jumps from "New Project" to a long uuid. See attached image:

Fixed

**Pull request merged**
