### PR TITLE
WIP: Feature/drag of image files on elementlist

### LINKED ISSUE #28: Drag-and-drop support for the placeholder component
- [ ] I should be able to drag a PNG or JPG from my local folder into the page element layers.

### PR DESCRIPTION
**Pull request by LKuechler**
…y on the element-list
Fixes #28

### CODE REVIEW

**Comment by tilmx** [comment]
Works fine for me!

**Comment by tilmx** [comment]
But can we only allow .png, .jpg and .svg to drop? Otherwise I can drag anything like an .zip or .app into Alva, but the placeholder doesn’t render any more.

**Comment by tilmx** [comment]
@LKuechler It does not indicate the drop zones any more when I drag an PNG or any other file onto the element pane. Before the latest change, you could see wether you drop it as a children or between. Can you reproduce that or should I attach a video?

**Comment by marionebl** [comment]
Closing as discussed with @LKuechler in person.

**Pull request closed without merging**
