### PR TITLE
feat: static deployments

### PR DESCRIPTION
**Pull request by marionebl**
Depends on #653 

## Proposed Changes
Short description of the changes:
* Add `node build/bin/alva --host=static`
* `node build/bin/alva --host=static export` creates static files in `export`
* Add complete `BrowserHost` with IndexedDB fs facade for browser persistence

### ToDo
- [x] Fix Protoype Export for `BrowserHost`
- [x] Take project path to preload with `node build/bin/alva --host=static export` 
- [x] Make branch names url-safe on CircleCI
- [x] Set up automatic deployments for branches / prs / master with distinct surge domains

### CODE REVIEW

**Comment by marionebl** [comment]
Deployed at: <strong>c5p7cr9dc9t62vk3d0ppctb1egqq6x31ehmp6bb4cnr6rvvtdnjpwx3k.surge.sh</strong>

**Comment by marionebl** [comment]
Deployed at: ctqpy.surge.sh

**Comment by marionebl** [comment]
Deployed at: https://ctqpy.surge.sh

**Comment by marionebl** [comment]
Deployed at: https://ctqpy.surge.sh

**Comment by marionebl** [comment]
Deployed at: https://ctqpy.surge.sh

**Comment by marionebl** [comment]
Deployed at: https://c5p7cr9dc9t62vk3d0ppctb1egqq6x31ehmp6bb4cnr6rvvtdnjpwx3k.surge.sh

**Comment by tilmx** [comment]
Amazing work @marionebl!
Just some bugs:

## Both: Electron & Node Environment
- [ ] When clicking on a page-switch link, the preview reacts, but the page list has still the old page highlighted.

## Only: Electron Environment
- [ ] When clicking on the App Icon in the app bar (macOS), Alva creates a new window, even though already a window was existing. This should only open a new window if no windows is already open.
- [ ] When creating a new file and saving it via "Cmd+S", no folder selection occurs where to save it, but the project is saved with the identifier.
- [ ] "Save As" does not work
- [ ] In the menu there are two reload functions (View -> ...) but they don't work. Should we remove them?
- [ ] "Cut" -> "Paste" does not work (Only cuts the element, does not copy it)
- [ ] After building Alva for Mac via `npm run build && npm run build:electron`, it does not show anything and does not open properly

## Only: Node Environment
- [ ] You can't click on "Create New Alva File" nor "Open File" on the Splash Screen (So I couldn't test any further)
- [ ] Clicking on a Page-Switch Link with Cmd+Click opens a new tab


Note: Closes #642, closes #643

**Comment by tilmx** [comment]
Copying between windows is really nice!
Just came across some other bugs:

## Node Environment
- [ ] Menu > New File opens Popup (Blocked by Chrome). Can we change that?
- [ ] Menu > New File. Add some stuff. Hit "Menu > Save As". Nothing happens.
- [ ] Select Element. Menu > Copy. Menu > Paste. Does not work. (Same for Paste Inside)

## Electron Environment
- [ ] "Open file" does not work if no window is open
- [ ] Opening a file "overwrites" the old window. It should open a new window instead
- [ ] Double-Clicking on the chrome for full-sizing does not work anymore :-(
- [ ] Create new file. Add some elements. Close the window. Alva should prompt you here (like before) if you want to save the file or not
- [ ] Create a new file. Add something. Save it. -> The Project name (in the chrome) does not change, even if I rename the project file.

Thanks <3

**Comment by marionebl** [comment]
>  Create new file. Add some elements. Close the window. Alva should prompt you here (like before) if you want to save the file or not

Just had an idea: As we actually persist the "draft" files in the app dir anyway, we could present the user with a list of said drafts on the splash screen and e.g. as new item ("Projects"?) in the main menu.

**Comment by tilmx** [comment]
Closes #650
Closes #645

**Pull request merged**
