### PR TITLE
feat: implement static html export

### LINKED ISSUE #72: Export as HTML
As a user I want to export the project as HTML files

### PR DESCRIPTION
**Pull request by marionebl**
This introduces a `Export to HTML` feature that enables export of the pages in the currently active project.

* **All** pages of the given project
* Generate a single HTML file with default name of the current 
* Navigate index-based through pages `#page-1` through `#page-[n]`
* Navigate id-based through pages `#[id]`

<details>
<summary>Screencast</summary>

html-export

</details>

Fixes #72

### CODE REVIEW

**Comment by tilmx** [comment]
Yippie! Works really well for me!

**Comment by TheReincarnator** [comment]
Superseded by #421.

**Comment by TheReincarnator** [comment]
Please note that, when merging this instead of #421, the contents of #421 are harder to integrate. Plus, I did bugfixing in #421's HTML-export commit that are not included here.

**Comment by TheReincarnator** [comment]
Please note that, when merging this instead of #421, the contents of #421 are harder to integrate. Plus, I did bugfixing in #421's HTML-export commit that are not included here.

**Comment by TheReincarnator** [comment]
Sorry, did not want to close, pressed wrong button.

**Comment by marionebl** [comment]
> @TheReincarnator  Please note that, when merging this instead of #421, the contents of #421 are harder to integrate. Plus, I did bugfixing in #421's HTML-export commit that are not included here.

Thanks for pointing this out. 👍  I am aware #421 will be harder to integrate. I guess we will port over your changes to a new PR manually to get a full grasp on what will change why.

**Comment by tilmx** [comment]
Can we name the menu as "Export Project as HTML" and the others "Export Page as..." with a seperation line between page and project actions? @marionebl

**Pull request merged**
