### PR TITLE
feat: enable automatic updates

### PR DESCRIPTION
**Pull request by marionebl**
Reenable automatic updates. Testing is rather involved, e.g. requires a Code Signing Certificate. Detailed instructions here:

https://meetalva.io/doc/docs/howtos/test-autoupdater.html?guides-enabled=true&eo4mrzjvyh-enabled=true

Related: https://github.com/meetalva/alva/issues/269

### CODE REVIEW

**Comment by marionebl** [comment]
Deployed at: https://alva-issues-701.surge.sh

**Comment by tilmx** [comment]
Hm, before merging this PR we should start an AWS machine for the endpoint, right? localhost:9000 is obviously only valid if running minio locally, right?

**Comment by marionebl** [comment]
dev-app-update.yaml only is used in dev Mode, so no real endpoint necessary

**Comment by tilmx** [comment]
Looks good! Let's open a window after a successfull update, so you see when the update is finished.

**Pull request merged**
